name: CI MX Contracts

on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  checks: write
  pull-requests: write

env:
  MX_DIR_PATH: packages/core/mx
  RUST_TOOLCHAIN: nightly-2022-12-08
  CLIPPY_ARGS: --all-targets --all-features

jobs:
  rust_test:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Run the rust tests
        env:
          RUSTFLAGS: ""
        run: |
          cd ${MX_DIR_PATH}
          cargo test

  clippy_check:
    name: Clippy linter check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
      - uses: giraffate/clippy-action@v1
        env:
          RUSTFLAGS: ""
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: ${{ env.CLIPPY_ARGS }}